# Generated by Django 5.0.6 on 2024-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('vendor_code', models.CharField(max_length=100)),
                ('on_time_delivery_rate', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
        ),
    ]
