# Generated by Django 5.1 on 2024-08-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendordetails',
            table='vendor_details',
        ),
    ]
