# Generated by Django 5.1 on 2024-08-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_alter_vendordetails_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendordetails',
            options={'verbose_name': 'vendor_details'},
        ),
    ]
